services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - APP_ENV=production
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/db/database.sqlite
    volumes:
      - ./db:/var/www/html/db
      - ./import.json:/app/import.json

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - app
