services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: ["php", "artisan", "octane:start", "--server=frankenphp", "--port=8080"]
    healthcheck:
      test: ["CMD", "healthcheck-octane"]
      start_period: 10s
    environment:
      - APP_ENV=production
      - MAIL_MAILER=log
      - OCTANE_HTTPS=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./database:/var/www/html/database
      - ./import.json:/app/import.json
    ports:
      - 8080:8080
