services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - APP_ENV=production
      - DB_CONNECTION=sqlite
      - DB_DATABASE=${DB_DATABASE:-/var/www/html/database/database.sqlite}
    volumes:
      - app-data:/var/www/html
      - ./import.json:/app/import.json

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - app-data:/var/www/html:ro

  scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler/Dockerfile
    command: [ "/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
    depends_on:
      - app
    environment:
      - APP_ENV=production
      - DB_CONNECTION=sqlite
      - DB_DATABASE=${DB_DATABASE:-/var/www/html/database/database.sqlite}
    volumes:
      - app-data:/var/www/html

volumes:
  app-data:
